@echo off
echo Initializing network environment...
wpeinit
echo Gathering PXE Server IP address...
cscript //nologo X:\sources\wds_server_ip.vbs > X:\Windows\wds_server_ip.log
set /p serverIpAddress=<X:\Windows\wds_server_ip.log
echo Connecting to PXE Server network directory...
net use N: \\%serverIpAddress%\PXEShare /user:WDSUser 6dEYN2HTvJ63xqkS
echo Load WDS Scripts...
start /b /wait N:\autounattend.cmd
exit